
apiVersion: apps/v1
kind: Deployment
metadata:
  name: t4-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: t4-con
      labels:
        env: production
    spec:
      containers:
      - name: t4-con
        image: priyanshigarg/webserver:latest
        
        
