apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t4-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: t4-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: t4-con
      labels:
        env: production
    spec:
      containers:
      - name: html-con
        image: priyanshigarg/webserver:v1
        volumeMounts:
        - name: web-vol1
          mountPath: /var/www/html
      volumes:
      - name: web-vol1
        persistentVolumeClaim:
           claimName: t4-pvc
        
